#!/bin/bash
rm -f ./log/qsortResults
touch ./log/qsortResults
rm -f ./log/bsortResults
touch ./log/bsortResults

for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
do
echo "Hello $i"
qsortResult=$(ladrun -np $i quicksortorbubblesortP 5000 100000 qsort)
printf "run $i" >> qsortResults
printf "$qsortResult" >> qsortResults

bsortResult=$(ladrun -np $i quicksortorbubblesortP 5000 10000 bsort)
printf "run $i" >> bsortResults
printf "$bsortResult" >> bsortResults
done
