#!/bin/bash
for i in 1 2 3
do
touch foo.bar
echo "Hello $i"
runAlgorithm=$(ladrun -np $i quicksortorbubblesortP 5000 100000 qsort)
printf "$i" >> algorithmsText
printf "$runAlgorithm" >> algorithmsText
done
