#!/bin/bash
rm -f ./foo.bar
touch foo.bar
for i in 25 26 27 28 29 30 31 32
do
echo "Hello $i"
runAlgorithm=$(ladrun -np $i quicksortorbubblesortP 5000 100000 qsort)
printf "run $i" >> foo.bar
printf "$runAlgorithm" >> foo.bar
done
